[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm_smart_contract = "BqQN1TNMcXdL9XsBbTpWtHn6TMhEq5kssmjDvFetVjoa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
